version: "2"

volumes:
  database:
  wordpress:

services:
  database:
    container_name: ${DOCKER_DATABASE_CONTAINER}
    image: mariadb
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - database:/var/lib/mysql

  wordpress:
    depends_on:
      - database
    container_name: ${DOCKER_WORDPRESS_CONTAINER}
    image: wordpress:latest
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    volumes:
      - ${VOLUME_BASE_PATH}/wp-content/mu-plugins:/var/www/html/wp-content/mu-plugins
      - ${VOLUME_BASE_PATH}/wp-content/plugins:/var/www/html/wp-content/plugins
      - ${VOLUME_BASE_PATH}/wp-content/themes:/var/www/html/wp-content/themes
      - wordpress:/var/www/html
